name: Python application - API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    name: Python ${{ matrix.python-version }} sample

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{matrix.python-version}}

    - name: Install poetry
      run: pipx install poetry

    - name: Clone Valkey
      uses: actions/checkout@v5
      with:
        repository: valkey-io/valkey
        path: valkey-tmp
        ref: "8.0"

    - name: Install and setup valkey
      run: |
        mv valkey-tmp ../valkey
        pushd ..
        pushd valkey
        make
        popd
        popd

    - name: Install with poetry
      run: |
        poetry install
        echo PROJECTNAME_HOME=`pwd` > .env
        poetry run start

    - name: Clone pyproject_template
      uses: actions/checkout@v5
      with:
        repository: Lookyloo/pyproject_template
        path: pyproject_template

    - name: Run API tests
      run: |
        pushd pyproject_template
        poetry install
        poetry run pytest tests/test_web.py
        popd

    - name: Stop instance
      run: |
        poetry run stop

    - name: Test update script
      run: |
        poetry run update --yes
        sleep 30
        poetry run stop
